#J2Cache configuration


#########################################
# Cache Broadcast Method
# values:
# jgroups -> use jgroups's multicast
# redis -> use redis publish/subscribe mechanism
#########################################

cache:
  broadcast: redis
  #########################################
  # Level 1&2 provider
  # values:
  # none -> disable this level cache
  # ehcache -> use ehcache as level 1 cache
  # redis -> use redis(hashs) as level 2 cache
  # [classname] -> use custom provider
  #########################################
  L1:
    provider_class: ehcache
  L2:
    provider_class: redis
  #########################################
  # Cache Serialization Provider
  # values:
  # fst -> fast-serialization
  # java -> java standard
  # [classname implements Serializer]
  #########################################
  serialization : fst
  #########################################
  # Redis connection configuration
  #########################################

  ## connection
  # redis.host 配置方式，需要根据 redis.policy 编写
  # single  host  127.0.0.1
  # sharded host  redis://password@127.0.0.1:6379/0  多个用逗号分割
  # cluster host  127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381

  #redis.host = localhost
  #redis.host = 39.107.106.122
redis:
  host : 127.0.0.1 #192.168.1.150
  port : 6379
  timeout : 7200
  # redis 部署策略 single 单机; cluster 集群; sharded 分片
  policy : single
  password :   #YLkjDouLin
  database : 1
  ## redis cache namespace optional, default[j2cache]
  namespace : j2cache
  ## redis channel name, 同一个redis server如果有多个使用J2Cache, 请保持channel name 的唯一性
  channel_name: j2cache_channel
  ## properties
  maxTotal: -1
  maxIdle: 2000
  maxWaitMillis: 100
  minEvictableIdleTimeMillis: 864000000
  minIdle: 1000
  numTestsPerEvictionRun : 10
  lifo: false
  softMinEvictableIdleTimeMillis: 10
  testOnBorrow: true
  testOnReturn: false
  testWhileIdle: false
  timeBetweenEvictionRunsMillis: 300000
  blockWhenExhausted: true

  #########################################
  # Ehcache configuration
  #########################################

ehcache:
  name: ehcache
  configXml: /j2cache/ehcache.xml